import = [
    "~/.config/alacritty/custom.toml"
]

[env]
TERM = "xterm-256color"

[font.bold]
family = "MesloLGSDZNerdFont"
style = "Bold"

[font.bold_italic]
family = "MesloLGSDZNerdFont"
style = "Bold Italic"

[font.italic]
family = "MesloLGSDZNerdFont"
style = "Italic"

[font.normal]
family = "MesloLGSDZNerdFont"
style = "Regular"
