[project]
name = "cast-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catt>=0.13.1",
    "pychromecast>=14.0.9",
    "rangehttpserver>=1.4.0",
]
